# Generated by Django 5.1.3 on 2024-12-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='keyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
                ('urlKeyWord', models.CharField(max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.TextField()),
                ('newsUrl', models.URLField()),
                ('newsDate', models.CharField(max_length=400)),
                ('isScraped', models.BooleanField(default=False)),
                ('newsAgency', models.CharField(max_length=500, null=True)),
                ('keyWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsApp.keywords')),
            ],
        ),
        migrations.CreateModel(
            name='newsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsarticle', models.TextField()),
                ('scrapingDate', models.DateField(auto_now=True)),
                ('gptSummary', models.TextField(null=True)),
                ('isEdited', models.TextField(null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsApp.newsmodel')),
            ],
        ),
    ]
